### ISSUE TITLE
Beim Start eines Level im Text unten ein Tippfehler.

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#101]
Dort steht: Löse das Level in möglichst wenig Zügen indem du alle schlagbaren Chips schlägst!
indem bitte trennen.

**Comment by rngShard** [comment]
Macht das den Satz nicht kaputt?

**Comment by Schreiber2000** [comment]
Verstehe nicht, es geht um das Wort "indem", das wird "in dem" geschrieben.

**Comment by rngShard** [comment]
http://www.duden.de/rechtschreibung/indem_weil_derweil, oder ich glaube ich verstehe deine Frage nicht. Geht ja nicht um "in dem Level", sondern "lösen indem man Chips schlägt". "in dem Level" ist sinngemäß komisch. Oder reden wir gerade aneinander vorbei? :/

**Comment by Schreiber2000** [comment]
ja so ist das mit der neuen Rechtschreibreform, da gibt es Sachen die nicht wirklich nachvollziehbar sind
