### ISSUE TITLE
Beim Spiel sind in den Zählern links die Zahlen so groß, das man sie nicht erkennen kann.

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#102]

**Comment by rngShard** [comment]
die schriftgroesse wird unterschiedlich gesetzt bei mobilen und nicht-mobilen greaeten. Kannst du kurz geraet und browser beschreiben? (oder optimaler weise screenshot anhaengen)

**Comment by Schreiber2000** [comment]
am iMac mit Safari, war übrigens früher korrekt dargestellt
