### ISSUE TITLE
Mehrspieler - Turm - Level 2.2, hier stellt sich eine grundsätzliche Frage (siehe Text)

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#108]
wenn zunächst alle grünen Chips geschlagen wurden, gelb alle blauen Chips geschlagen hat und blau noch nicht, ist dann, wie es gerade eingerichtet ist, das Spiel zu Ende? Oder kann noch weitergespielt werden?
Die Aufgabenstellung war nämlich, wer schlägt die meisten und nicht wer hat als erster die gegnerischen Chips als erstes geschlagen.

**Comment by rngShard** [comment]
Aktuell ist "Das spiel ist beendet sobald eine Partei alle von Ihr schlagbaren Chips geschlagen hat. Es gewinnt nun der mit den meisten geschlagenen Chips. Wenn eine figur geschlagen wird und eine Partei keine Figuren mehr besitzt gewinnt die andere Partei."
Habe fuer Di notiert was wir bezueglich Siegbedingungen besprechen koennten, das hier ist mit dabei. Wuerde das Issue hier so schliessen und auf Dienstag verweisen ^^
