### ISSUE TITLE
Mehrspieler - mit je 2 Läufern mit schlagen, diese Aufgabe stellt ein Problem dar (siehe Text)

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#111]
wenn gelb einen Läufer verliert und dann der blaue ebenfalls, kann der andere Läufer (der auf den gelben Feldern) nicht die auf den blauen Feldern schlagen und das auf beiden Seiten. Wenn es aber noch Chips auf den blauen Feldern gibt, wird die Partie nicht entschiedenen und es kann unendlich gespielt werden. In diesem Fall müßte das System das Spiel abbrechen und die Chips zählen und den Sieger bestimmen.

**Comment by rngShard** [comment]
Auch hier wieder (vergleichbar mit anderen aufgaben): "Das system muss das spiel abbrechen und den Gewinner bestimmen" ist nicht implementierbar. Bisher ist das Spielende automatisch bestimmt wenn eine partei alle chips seiner schlagbaren farbe und alles gruene geschlagen ist oder die figuren selbst alle genommen wurden. Sonst nicht! Alles weitere ist zwar aus menschlicher SIcht ("da komm ich doch garnicht mehr ran, mein lauefer hat die falsche Farbe, aber ich hab doch eh mehr chips als der andere") sinn, aber automatisch das SPiel zu beenden (ohne dass der spieler zeit hat zu realisieren warum, vll sieht er ja garnicht, dass der lauefer die falsche farbe hat) waere auch falsch. Dafuer gibt es den Aufgeben-Button. Oder du kannst genaue Abbruchbedingungen spezifizieren und wir versuchen das zu implementieren. Waere aber guter Diskussionsbedarf fuer Dienstag. Da koennen wir generell durch alle offenen Issues gehen und besprechen wo grundlegende Fragen aufkommen.
