### ISSUE TITLE
Mehrspieler - Lauefer - Level 3.1, wenn eine Partei alle möglichen Chips geschlagen hat, ist die Partie nicht zu Ende

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#112]

**Comment by Schreiber2000** [comment]
vermutlich müssen wir diese Aufgabe löschen

**Comment by rngShard** [comment]
Das level macht in der Tat nach den aktuellen Gewinnbedingungen wenig Sinn, mit anderstfarbigen laeufern gibt es kein konkurenzverhalten sondern jedem sind seine gruenen chips sicher. Wenn alle schwazfeldrigen chips blau statt gruen waeren und alle weissfeldrigen chips gelb wuerde die aufgabe auch sinngemaess passen ("wer schlaegt seine schlagbaren chips effektiver"). Das level ist auch wieder ein gutes beispiel wo "schlagbar/unschlagbar" irrelevant wird. Trotzdem ist die auswahl allgemein fuer alle mehrspielerlevel moeglich zu machen die ellegantere loesung ... 
@Schreiber2000 Level loeschen oder chips-farben anpassen?
