### ISSUE TITLE
Mehrspieler - Springer - Level 6.1, bei dieser Aufgabe muss die Möglichkeit "Figuren schlagbar" raus

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#113]

**Comment by rngShard** [comment]
Das manuelle ausschalten von schlagmoeglichkeiten von leveln ist richtig unschoen zu implementieren, da muss dann im Code explizit nach (wenn Level 6.1 von Springer, dann das und das ausschalten) gefiltert werden. Gerade geschaut, das level macht im Schlagen wenig Sinn. Aber das hart da reinzuschreiben ist seeeeeeeeeeehr unschoen ... Kann das Level nicht angepasst werden, dass es auch mit schlagbar sinn macht? (bspw. die spirnger jeweils gegenueber auf d3 & e6 oder d3 & d6 stellen?)

**Comment by rngShard** [comment]
@Schreiber2000 da wie am Dienstag besprochen einige Level fuer Schlagen / Nicht-Schlagen wenig sinn machen: koenntest du uns eine Uebersicht geben der Level die du nicht aendern willst und wo es hilfreich waere eine der beiden optionen auszuschalten? dann koennten wir die option in dem Eigenschaften der Level in der Datenbank speichern und in der Auswahl des Modus nutzen. Was denkst du?

**Comment by rngShard** [comment]
Level angepasst, sodass spielbar. @Schreiber2000 bitte anschauen (http://agenodrei.de:4000/de/mp/knight/mp_knight_06_01), gefaellt mir so auch deutlich besser ^^
