### ISSUE TITLE
Auch beim den Bauern-Aufgaben (Mehrspieler) muss das Spiel beendet werden, wenn einer nicht mehr ziehen kann!

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#114]

**Comment by rngShard** [comment]
Wurde bereits angesprochen, letzter Stand den wir hatten war "es wird von den Spieler bemerkt dass keiner Mehr ziehen kann und das Level wird aufgegeben". Problematik: Wer hätte gewonnen wenn automatisch abbrechen?? Pädagogischer Mehrwert von selbst erkennen dass Level beendet
