### ISSUE TITLE
Mehrspieler Lokal - Minischach "Geschickte Bauern" dieses Spiel endet nicht

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#124]

**Comment by rngShard** [comment]
Endet sobald gelb die letzte Reihe erreicht, blau wird grad außen vor gelassen. Hatte bereits ne Diskussion mit Simon, wird für blau angepassst. War das das Issue?

**Comment by Schreiber2000** [comment]
genau

**Comment by rngShard** [comment]
@AgenoDrei hatten wir ja bereits besprochen, bitte Gewinnbedingung entsprechend anpassen kurz!
