### ISSUE TITLE
Habe ein neues Minischach eingegeben, taucht aber nicht unter "Brandneue Level..." auf

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#125]

**Comment by rngShard** [comment]
"Dame gegen Bauer" wird angezeigt, es kann sein dass du die seite neu laden musst nachdem du das level erstellt hast (falls du das Menü bereits offen hattest bevor das level erstellt war). War das der Fall? War das das level?

**Comment by Schreiber2000** [comment]
Seite habe ich natürlich neu geladen, "Dame gegen Bauer" erscheint trotzdem nicht

**Comment by rngShard** [comment]
Erscheint aktuell im Modal.

Bin am anpassen der Dinge die wir besprochen hatten, damit wird dann das Erstellen von Minischachleveln ja rausfallen (option im Editor rausnehmen), das Modal mit "Dame gegen Bauer" wird damit auch wieder verschwinden.

Wenn du Level erstellst, einfach als Einzel/Mehrspieler erstellen uns die Gewinnbedingung schreiben (per mail / per github / ...) und wir koennen das dann reviewen.

Ist das ok so?

**Comment by rngShard** [comment]
Die eigentliche idee die neuen Minischachlevel einzupflegen  wird ja in #123 bereits besprochen

**Comment by Schreiber2000** [comment]
ist jetzt zu sehen, man muss allerdings erst auf "Brandneue Level aus....." klicken
