### ISSUE TITLE
Sorry, würde jetzt aus bestimmten Gründen doch den Editor auch für Minischach aktiviert haben.

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#128]

**Comment by rngShard** [comment]
Hab's mir fast schon gedacht, ein Großteil des Codes hab ich nur auskommentiert und nicht gelöscht ;)
Jetzt auch mit Auswahl der Siegesbedingung und ist auch direkt Spielbar ^^
