### ISSUE TITLE
Kontakt-Daten bei Editor hinterlegen koennen!

### ISSUE THREAD

**Issue by rngShard** [AgenoDrei/ChipschachDigital#156]

**Comment by Schreiber2000** [comment]
Könnt Ihr mir bitte mitteilen. wann ich damit rechnen kann? Davon hängt die Aktion mit dem Deutschen Schachbund ab.

**Comment by rngShard** [comment]
Sry für das späte Melden, aktuell ist Abgabetermin der Bachelorarbeit und Umzugs-/Wohnungssuchstress.
Ich werde mich diesen Donnerstag dransetzen, mit ein bisschen Glück ist es dann am späten Do Abend auch schon fertig!

**Comment by rngShard** [comment]
Ist in v2.4.1 eingepflegt (aktuell auf development-branch)

**Comment by Schreiber2000** [comment]
Sorry, aber ich sehe nichts

**Comment by rngShard** [comment]
agenodrei.de:4000
da das ein einzelnes Feature ist wurde es zunächst in den development-branch gepusht. Auf development sitzt agenodrei mit webhook drauf. Soll das auch direkt in den Master (wo schach-fuer-kids drauf sitzt) integriert werden?

**Comment by Schreiber2000** [comment]
Naja, wenn die Leute an einem Preisausschreiben mitmachen sollen, dann müssen wir es nicht nur veröffentlichen, wir benötigen auch die gesamten Daten, also Adresse. Die Frage ist, ob sogar das Alter oder zu mindestens ob die Person über oder unter 18 Jahre alt ist, abgefragt wird. Irgendwo sollte noch der Hinweis erscheinen, das wir die Dann nur für die Verlosung von preisen nutzen. Ist es da nicht besser, wenn für die Eingabe mit dem Hinweis in einem neuem Fenster erscheint??

**Comment by rngShard** [comment]
Wozu braucht man denn Adresse direkt angeben? Willst du da einfach pro-forma alle Daten der Teilnehmer abgreifen? Wer gewonnen hat wird per angegebener Kontaktmöglichkeiten kontaktiert dachte ich... Adresse wird bei verschicken von Preisen etc dann ggf. per Mail ausgetauscht?

In nen externes Fenster bricht den Fluss des Editors ein wenig. Und wir hätten dann wiederum eine extra Kleinigkeit die nicht in die gesammt App reinpasst. Und ist mit externem Fenster auch entsprechend mehr Aufwand.

**Comment by Schreiber2000** [comment]
dann macht doch noch eine Zeile für die Adresse rein und unabhängig davon sollte das mit dem Alter geklärt werden! Vielleicht mit einem Haken bei über 18 Jahren. Wo landen eigentlich die Daten und wie komme ich dran?

**Comment by rngShard** [comment]
Füge gleich beides hinzu. Daten landen in der Datenbank im gleichen Dokument wie das erstellte level

**Comment by rngShard** [comment]
sobald simon den merge freigibt wird es im master sein und du kannst es auch auf schach-fuer-kids sehen

**Comment by Schreiber2000** [comment]
soweit ok, bitte noch den Text ändern in:
Ich möchte an einer Verlosung teilnehmen, die besten Stellungen gewinnen Preise.

Ich davon aus das die Stellungen dann auch den Adressen zugeordnet sind.

**Comment by Schreiber2000** [comment]
Ach so, der Button zum Speichern muss dann ganz nach unten, sonst klickt man zu früh drauf und versucht erst dann seine Adresse einzugeben.

**Comment by rngShard** [comment]
Ok, Änderungen werden Montag eingepflegt. So kleine Anpassungen zerstören die wartbarkeit der Änderungen komplett. Ist ab Montag Abend drin.
