### ISSUE TITLE
Die Aufgaben bzw. die Datenbank ist nicht mehr zugeordnet, es gibt quasi keine Aufgaben

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#162]

**Comment by rngShard** [comment]
Immernoch? gerade getestet, scheint wieder zu gehen

**Comment by Schreiber2000** [comment]
geht wieder, bedankt, vielleicht erklärt Ihr mir mal wie ich in diesem Fall das selber reparieren kann

**Comment by rngShard** [comment]
Laut Simon ein Verbindungsfehler mit der Datenbank, ein restart fix es dann. Wissen aber noch nicht genau woran es liegt, könnte allg. an den Datenbank settings liegen
