### ISSUE TITLE
Aufgabenfenster nicht mittig

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#31]

**Comment by rngShard** [comment]
Das Aufgabenfenster ist mittig mit der Seitenleiste mit einbezogen. Willst du das Aufgabenfenster mittig im nSinne von "breite der Seitenleiste ignorieren und mittig zum gelben hintergrund"?

**Comment by Schreiber2000** [comment]
Das Brett ist inzwischen mittig, alles ok. Jetzt müßte das Brett z.B. auf dem Tablet oder auch auf dem Handy komplett sichtbar sein. Hinzu kommt, das mann es auch nicht verschieben kann.

**Comment by rngShard** [comment]
Sehr gut! Damit schliesse ich das issue hier dann mal ^^
