### ISSUE TITLE
wenn eine Figur aktiviert wurde, hebt sich das im nächstem Zug auf, korrigieren.

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#32]

**Comment by rngShard** [comment]
Noticed switchSelection never accounts for whom's turn it is. Would have to save 2 player selections and account for it without perse switching selection. (CAUTION: clear selection if figure is being beaten!)
Reassigned to Simon as it involves some little Pixi Magic.
