### ISSUE TITLE
Mehrspieler bitte zuvor entscheiden lassen ob mit oder ohne schlagen der gegnerischen Figur.

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#35]

**Comment by rngShard** [comment]
Was meinst du mit "zuvor entscheiden"?

**Comment by Schreiber2000** [comment]
früher habe ich die Aufgabe aufgerufen, dann konnte ich anklicken ob ich mit schlagen oder ohne schlagen spielen möchte, jetzt ist es so, das erst alle Aufgaben aufgerufen werden ich dort etnscheide ob mit oder ohne schlagen.

**Comment by rngShard** [comment]
ist im issue https://github.com/AgenoDrei/ChipschachDigital/issues/14 bereits angedacht
