### ISSUE TITLE
Patt für Chipschachlevel

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#38]

**Comment by rngShard** [comment]
@Schreiber2000 habe gerade den Aufgeben-Button implementiert. Ich dachte mir dabei gerade, dass es doch einen paedagogischen Mehrwert haette wenn ein Spieler selbst bemerkt dass kein Moeglicher zug mehr existiert und er entscheidet er muesse aufgeben und nochmal nue versuchen. Wuerde das dieses Problem loesen?

**Comment by Schreiber2000** [comment]
ist für die Kinder in dem Alter leider schlecht, wir hatten in der alten Version ja auch eine entsprechende Meldung, vielleicht dort einmal nachschauen.
