### ISSUE TITLE
Kann ich in Zukunft selber Levels/Aufgaben eingeben?

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#45]

**Comment by rngShard** [comment]
Der Editor ist fuer nach der Beta eingeplant, mit der aktuellen ordnerstruktur werden deine Level dann (solang sie in die aktuelle Struktur mit Bauer/Springer/...-Kategorie und Singleplayer/Multiplayer/Minischach passt) direkt in das menu mit aufgenommen
