### ISSUE TITLE
Menü Mitte SfK-Button, Logo bitte nicht strecken

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#49]

**Comment by rngShard** [comment]
Was meinst du mit "gestreckt"? Das SfK-Icon ist fuer den Button in der Mitte, & den Link im Impressum (wenn auf mitte geklickt) das gleiche Bild bei dem das Verhaeltnis Hoehe-Breite gleich ist.
Oder hab ich die Frage falsch verstanden?

**Comment by Schreiber2000** [comment]
das Logo wirkt, als hätte jemand mit dem Hammer drauf gehauen, also zu breit

**Comment by rngShard** [comment]
Hab die aufloesung angepasst, sollte jetzt passen
