### ISSUE TITLE
Impressum Beteiligte wie folgt ändern

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#77]
Initiator: Ralf Schreiber, SfK
Leitung: Peter Kusterer, IBM
Programmierung: Simon Müller, IBM
Programmierung: Oliver Berg, IBM

**Comment by rngShard** [comment]
Peter hsat gemeint er sieht sich auch als Initiator, und Leitung seie nicht ganz akurat, daher die letzte aenderung der Rollenbeschreibung.
Soll ich es trotzdem wieder auf wie oben zuruecksetzen?

**Comment by Schreiber2000** [comment]
würde ich machen, es ist ja auch so

**Comment by rngShard** [comment]
Ok. Darf ich die klammern hinten lassen und bei peter wieder leitung mit reinnehmen statt dem [Funktion]: [Name] ?

**Comment by rngShard** [comment]
also 
`[Name] ([Funktion])`
statt
`[Funktion]: [Name]`
?

**Comment by Schreiber2000** [comment]
ist ok

**Comment by rngShard** [comment]
gut. Ist geaendert. kommt in 2.2.3 dann rein.
