### ISSUE TITLE
Aufgabenfenster wie früher bitte mittig und etwas transparent einstellen, siehe Anlagen alt, neu

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#78]
<img width="1596" alt="alt" src="https://cloud.githubusercontent.com/assets/17127941/24402495/29cabf6e-13b9-11e7-9cfe-8957656dc770.png">

**Comment by rngShard** [comment]
Das aktuelle aufgabenfenster kann leicht durchsichtig gemacht werden, kein Problem. Das Fenster ist mittlerweile eine standart-komponente, die automatisch *zum Browserfenster* zentriert wird. Wenn (bspw. auf dem Laptop, wenn der Bildschirm gross genug ist) die seitenleiste links nicht automatisch eingefahren wird (wie bei handy) ist das fenster damit nicht zentral zum Brett. Es ist ausserdem horizontal mittig, da das standart-design ist, vertikale zentrierung ist in der Programmierung immer sehr unschoen, daher is das dort auch kein Standart.

Um das fenster **immer** mittig ueber dem Brett zu haben muessten wir unsre alte version nehmen und koennten die Standartisierten Komponenten nicht benutzen. Die garantieren uns aber bspw. auch eine schoene anzeige auf dem handy, unsere manuelle version kann das nicht.

Wie wichtig ist dir das Aufgabenfenster mittig ueber dem Brett?? Die aktuelle variante ist vom Programmierstanpunkt naemlich sehr schoen :(

**Comment by rngShard** [comment]
Fenster ist durchsichtig gemacht worden. kommt in naechster version mit rein.

**Comment by Schreiber2000** [comment]
überlege ich noch einmal, es ist so das auf dem Monitor das versetzte Fenster komisch wirkt.

**Comment by rngShard** [comment]
Ggf. kann das brett mit beschreibung auch komplett ausgeblendet werden und erst beim klicken auf den button - wenn das modal verschwindet - angezeigt werden. Damit ist das Modal dann nicht iwie schraeg ueber dem brett sondern auf einem blanken hintergrund.

**Comment by Schreiber2000** [comment]
mach das mal so, mal sehen wie es ausschaut, kann im Notfall ja wieder geändert werden

**Comment by rngShard** [comment]
ok, ist drin. Sieht ganz ok aus, kannst du dir mit 2.2.3 ja mal anschauen ^^

**Comment by Schreiber2000** [comment]
das könnte man so machen, wenn es denn auch bei den weiteren Levels das Schachbrett auch ausgeblendet wird
