### ISSUE TITLE
Ab und zu bekomme ich das abgebildete Fenster

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#81]
Betriebssystem mac OS Sierra 10.12.3 (16D32)
Browser Firefox 52.0.1 (64-Bit)
![chipschach](https://cloud.githubusercontent.com/assets/17127941/24491885/90e1de3c-1529-11e7-855a-4854889143ba.png)

**Comment by Schreiber2000** [comment]
Inzwischen bekomme ich dieses Fenster nur noch und bei allen Aufgaben. Ich kann also zur Zeit überhaupt nicht mehr spielen bzw. testen.

**Comment by rngShard** [comment]
Das blanke Brett ist das Standart he Hintergrund Bild, wenn das level nicht korrekt initialising wird bleibt das "Leere Brett" erhalten. Dass es so krass falsch skaliert ist wiederum besorgniserregend. Ich schau's mir gleich kurz an

**Comment by rngShard** [comment]
@Schreiber2000 bekommst du das abgebildete Bild immernoch? Wenn ja, wie?
