### ISSUE TITLE
Chipschach und ChipschachDigital

### ISSUE THREAD

**Issue by poldemo** [AgenoDrei/ChipschachDigital#82]
Wieso sind eigentlich zwei Repositories auf github? Ich hatte meine Issues bisher im anderen eingegeben....

**Comment by rngShard** [comment]
"Chipschach" ist die alte, traditionelle Version, "ChipschachDigital" ist das neue, vom Prototypen losgelöst, schöner geschriebene und wartbare Version

**Comment by rngShard** [comment]
Dadurch dass die Architektur umgekrempelt wurde um auch tatsächlich mal "schönen" code zu haben, wollten wir ein neues Projekt aufsetzen.
