### ISSUE TITLE
Wenn eine Aufgabe gelöst ist, bitte im Fenster einen Button einbauen mit dem man die Aufgabe wiederholen kann

### ISSUE THREAD

**Issue by Schreiber2000** [AgenoDrei/ChipschachDigital#99]

**Comment by rngShard** [comment]
Button existiert bereits, wird allerdings nur bei beenden eines lvls mit nicht minimaler Zugzahl angezeigt, sonst ausgeblendet. Willst du das geändert haben? Wenn ja, woran genau denkst du?

**Comment by Schreiber2000** [comment]
Ich denke das wir das bei jeder Aufgabe anbieten sollten.

**Comment by rngShard** [comment]
ist eingebaut, man kann jetzt egal wie gewonnen wurde im einzelspieler das level wiederholen. Ist in Verison 2.2.5
